baseurl = "http://www.xbuf.org/"
languageCode = "en-us"
title = "xbuf"
theme = "hyde"
canonifyurls = true

[params]
  Description = "An exchange format for 3D scenes, models, animations, …"
  Author = "David Bernard"
  Copyright = "Public domain (CC0-1.0)"
